Feature
rashedarman/capstone-m1 pull request #1
Opened 2022-12-03 21:57 UTC by rashedarman

- Created home and about page with responsive breakpoints
- Mobile menu has a close (X) button that closes the menu
- Respective sections are created dynamically using JavaScript
- Linters are properly configured and errors were fixed

2022-12-03 22:49 UTC, Olamarx requested changes
Hi @rashedarman,

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media1.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

## Highlights
- All linters passed ✅
- Commit messages ✔️ 
- Reame file ✔️ 


## Required Changes ♻️
_Check the comments under the review._
- [ ]  You have probably forgotten the 5 mins video. I would advise you to add it.
- [ ] Kindly always stick to the design look generally as it would help you in the industry and you would be able to adhere to project requirements.
- [ ] I am unable to access the about section at all just because the path is not added properly. I left a comment under it.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 22:49 UTC, Olamarx commented on index.html
> +                <a href="/about.html" class="nav-link">About</a>
- [ ] This path is not getting linked to the about section and as a result, it can't be accessed both through the GitHub deployed page and even by my way of reviewing it. Kindly make it `./about.html` or just `about.html`.

2022-12-03 22:49 UTC, Olamarx commented on index.html
> +          <a href="/" class="navbar-brand d-none d-md-flex">
- [ ] I think you forgot to add the top dark bar. It is actually part of the design.
![image](https://user-images.githubusercontent.com/86200356/205464699-c2be236e-d214-40c8-b8b6-396ce986f402.png)

2022-12-03 22:49 UTC, Olamarx commented on index.html
> +      </section>
- [ ] Kindly add all the content just as it is in the Behance design. But you should make the content fit your project just as you have done but some contents are missing. The Behance has 5 different content and no button, but your design has two contents and one button. 
### Behance
![image](https://user-images.githubusercontent.com/86200356/205464879-fd30a39d-da35-450b-bd1a-d6c7464ede83.png)

### Your design
![image](https://user-images.githubusercontent.com/86200356/205464894-34f334e5-11a4-44c2-8e77-c84691f8adde.png)

2022-12-03 22:49 UTC, Olamarx commented on index.html
> +            </div>
- [ ] Kindly add alternative names to all the img tags. With this, other devices such as screen readers would be able to access it.

2022-12-03 22:49 UTC, Olamarx commented on technologies.js
> +const technologiesData = [
- [ ] This technology data should be 6 in number so that it would match the design.

2022-12-03 23:01 UTC, rashedarman commented on technologies.js
> +const technologiesData = [
It is actually the features section that should be 6 in number. But I get the point, I will add the changes thanks.

2022-12-04 00:52 UTC, Bondok6 requested changes
## Hi @rashedarman 🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

 ## Required Changes ♻️
 
- [ ] As the previous reviewer mentioned and according to the requirements, you should record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

- A description of the project.
- A demo of the project features (different pages and different screen sizes).
- You should also highlight some interesting piece of code or something you built that you are very proud of.

![image](https://user-images.githubusercontent.com/45231276/205468404-5c52b7d7-8aa0-4bcc-9fd9-1d4f5215341e.png)


## Optional suggestions

- [ ] _Check the comments under the review._ ⬇

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-04 00:52 UTC, Bondok6 commented on about.html
> +    </footer>
- [OPTIONAL] Great job here 💯 However, According to the [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)

- About page should contain both the `Partner` section and white `Footer` section in `Mobile Version`, so I suggest adding the partners section and changing the bg-color of footer section to white in mobile version. 👍

> I marked this as optional, because it's missed by the previous reviewer. However, I strongly recommend you to take them into account as they can make your code better.

2022-12-04 00:52 UTC, Bondok6 commented on index.html
> +      </section>
- [OPTIONAL] Great job implementing the technologies section dynamically using JS, I suggest suggest to add button at the end of the section to follow the original design 💯

> Desktop Version
![image](https://user-images.githubusercontent.com/45231276/205468448-c515327c-dfe1-465d-b6bb-d1361f4493a5.png)
>Mobile Version
![image](https://user-images.githubusercontent.com/45231276/205468469-1cdf9259-02be-4514-bd0e-3771bc7388f1.png)

> I marked this as optional, because it's missed by the previous reviewer. However, I strongly recommend you to take them into account as they can make your code better. 💡

2022-12-04 02:17 UTC, arslanbisharat commented
Hi @rashedarman,
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-04 02:20 UTC, merged